// This file contains all the odd parts used by the sequencer that
// aren't in the normal decoder laser parts. This also doesn't include
// cams, which are autogenerated outside this repository at the
// moment.

include <globs.scad>;
include <sequencer_globs.scad>;
use <sequencer.scad>;

$fn=20;

kerf = 0.08;
offset(r=kerf) {
  follower_comb_2d();
}


